package firstboot

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// The two documents below are generated by string formatting, which is easy to
// get subtly wrong -- a missing quote, a miscounted space. So every test here
// PARSES the result rather than searching it for a substring: a document that
// does not parse is not a document kubeadm or the kubelet will accept.

type kubeadmDoc struct {
	Kind             string `yaml:"kind"`
	APIVersion       string `yaml:"apiVersion"`
	LocalAPIEndpoint struct {
		AdvertiseAddress string `yaml:"advertiseAddress"`
		BindPort         int    `yaml:"bindPort"`
	} `yaml:"localAPIEndpoint"`
	NodeRegistration struct {
		Name      string `yaml:"name"`
		CRISocket string `yaml:"criSocket"`
	} `yaml:"nodeRegistration"`
	KubernetesVersion    string `yaml:"kubernetesVersion"`
	ControlPlaneEndpoint string `yaml:"controlPlaneEndpoint"`
	Networking           struct {
		PodSubnet string `yaml:"podSubnet"`
	} `yaml:"networking"`
}

func parseKubeadmDocs(t *testing.T, raw []byte) []kubeadmDoc {
	t.Helper()
	var docs []kubeadmDoc
	for chunk := range strings.SplitSeq(string(raw), "\n---\n") {
		chunk = strings.TrimSpace(chunk)
		if chunk == "" {
			continue
		}
		var d kubeadmDoc
		if err := yaml.Unmarshal([]byte(chunk), &d); err != nil {
			t.Fatalf("generated kubeadm document does not parse: %v\n%s", err, chunk)
		}
		docs = append(docs, d)
	}
	return docs
}

func TestKubeadmConfigIsValidAndCorrect(t *testing.T) {
	cfg := loadConfig(t, masterDoc)
	raw, err := KubeadmConfig(cfg, "vates-cp-1", "192.168.122.50")
	if err != nil {
		t.Fatalf("KubeadmConfig() failed: %v", err)
	}

	docs := parseKubeadmDocs(t, raw)
	if len(docs) != 3 {
		t.Fatalf("generated %d documents, want 3 (Init, Cluster, Kubelet)", len(docs))
	}

	init := docs[0]
	if init.Kind != "InitConfiguration" {
		t.Errorf("first document kind = %q, want InitConfiguration", init.Kind)
	}
	if init.LocalAPIEndpoint.AdvertiseAddress != "192.168.122.50" {
		t.Errorf("advertiseAddress = %q, want the node's own address", init.LocalAPIEndpoint.AdvertiseAddress)
	}
	if init.LocalAPIEndpoint.BindPort != 6443 {
		t.Errorf("bindPort = %d, want 6443", init.LocalAPIEndpoint.BindPort)
	}
	if init.NodeRegistration.Name != "vates-cp-1" {
		t.Errorf("nodeRegistration.name = %q, want vates-cp-1", init.NodeRegistration.Name)
	}
	// kubeadm must be told to use containerd; it would otherwise assume the
	// default socket and fail to find the CRI.
	if init.NodeRegistration.CRISocket != CRIEndpoint {
		t.Errorf("criSocket = %q, want %q", init.NodeRegistration.CRISocket, CRIEndpoint)
	}

	cluster := docs[1]
	if cluster.Kind != "ClusterConfiguration" {
		t.Errorf("second document kind = %q, want ClusterConfiguration", cluster.Kind)
	}
	// The endpoint is the VIP, not the node's address: that is the whole point
	// of the VIP, and confusing the two would put a single node's address into
	// every certificate's SAN list.
	if cluster.ControlPlaneEndpoint != "192.168.1.10:6443" {
		t.Errorf("controlPlaneEndpoint = %q, want the configured endpoint", cluster.ControlPlaneEndpoint)
	}
	if cluster.KubernetesVersion != "v1.31.0" {
		t.Errorf("kubernetesVersion = %q, want v1.31.0", cluster.KubernetesVersion)
	}
	if cluster.Networking.PodSubnet != "10.244.0.0/16" {
		t.Errorf("podSubnet = %q, want the configured CNI CIDR", cluster.Networking.PodSubnet)
	}

	if docs[2].Kind != "KubeletConfiguration" {
		t.Errorf("third document kind = %q, want KubeletConfiguration", docs[2].Kind)
	}
}

func TestKubeVIPManifestIsValidAndCorrect(t *testing.T) {
	raw, err := KubeVIPManifest("192.168.122.99", "eth0", "6443", SuperAdminKubeconfig, "192.168.122.252", KubeVIPImage)
	if err != nil {
		t.Fatalf("KubeVIPManifest() failed: %v", err)
	}

	var pod struct {
		Kind     string `yaml:"kind"`
		Metadata struct {
			Name      string `yaml:"name"`
			Namespace string `yaml:"namespace"`
		} `yaml:"metadata"`
		Spec struct {
			HostNetwork bool `yaml:"hostNetwork"`
			Containers  []struct {
				Name  string   `yaml:"name"`
				Image string   `yaml:"image"`
				Args  []string `yaml:"args"`
				Env   []struct {
					Name  string `yaml:"name"`
					Value string `yaml:"value"`
				} `yaml:"env"`
				SecurityContext struct {
					Capabilities struct {
						Add []string `yaml:"add"`
					} `yaml:"capabilities"`
				} `yaml:"securityContext"`
				VolumeMounts []struct {
					MountPath string `yaml:"mountPath"`
				} `yaml:"volumeMounts"`
			} `yaml:"containers"`
			Volumes []struct {
				HostPath struct {
					Path string `yaml:"path"`
				} `yaml:"hostPath"`
			} `yaml:"volumes"`
		} `yaml:"spec"`
	}
	if err := yaml.Unmarshal(raw, &pod); err != nil {
		t.Fatalf("generated kube-vip manifest does not parse: %v", err)
	}

	if pod.Kind != "Pod" || pod.Metadata.Name != "kube-vip" || pod.Metadata.Namespace != "kube-system" {
		t.Errorf("manifest identifies %s/%s (%s), want kube-vip in kube-system as a Pod",
			pod.Metadata.Namespace, pod.Metadata.Name, pod.Kind)
	}
	// Without hostNetwork the pod cannot add the address to the host's interface
	// at all.
	if !pod.Spec.HostNetwork {
		t.Error("hostNetwork is not set; kube-vip cannot manage the host's address")
	}
	if len(pod.Spec.Containers) != 1 {
		t.Fatalf("got %d containers, want 1", len(pod.Spec.Containers))
	}
	c := pod.Spec.Containers[0]

	env := map[string]string{}
	for _, e := range c.Env {
		env[e.Name] = e.Value
	}
	want := map[string]string{
		"vip_arp":            "true",
		"address":            "192.168.122.99",
		"port":               "6443",
		"vip_interface":      "eth0",
		"vip_subnet":         "32",
		"cp_enable":          "true",
		"vip_leaderelection": "true",
	}
	for k, v := range want {
		if env[k] != v {
			t.Errorf("env %s = %q, want %q", k, env[k], v)
		}
	}

	caps := map[string]bool{}
	for _, cap := range c.SecurityContext.Capabilities.Add {
		caps[cap] = true
	}
	for _, want := range []string{"NET_ADMIN", "NET_RAW"} {
		if !caps[want] {
			t.Errorf("capability %s is missing; kube-vip cannot manipulate the interface without it", want)
		}
	}

	if c.Image != KubeVIPImage {
		t.Errorf("image = %q, want the pinned %q", c.Image, KubeVIPImage)
	}
	// The mount is asymmetric, and that is the point: kube-vip reads a FIXED
	// container path, while the host path is ours to choose. Asserting they are
	// equal -- which an earlier version of this test did -- encodes the bug that
	// made kube-vip unable to find its kubeconfig at all.
	if len(c.VolumeMounts) != 1 || c.VolumeMounts[0].MountPath != kubeVIPContainerKubeconfig {
		t.Errorf("volumeMounts = %+v, want one at %s (the path kube-vip reads)",
			c.VolumeMounts, kubeVIPContainerKubeconfig)
	}
	if len(pod.Spec.Volumes) != 1 || pod.Spec.Volumes[0].HostPath.Path != SuperAdminKubeconfig {
		t.Errorf("volumes = %+v, want one hostPath at %s", pod.Spec.Volumes, SuperAdminKubeconfig)
	}
	if kubeVIPContainerKubeconfig == SuperAdminKubeconfig {
		t.Error("the container and host paths are equal; kube-vip mounts one at the other and they are not the same")
	}
}

func TestKubeVIPFindsItsKubeconfig(t *testing.T) {
	// kube-vip loads its kubeconfig from a FIXED container path,
	// /etc/kubernetes/admin.conf. That path is not a setting: its own manifest
	// generator hardcodes it and uses K8sConfigFile only for the host side. So
	// the manifest must mount our host file AT that path.
	//
	// Setting k8s_config_file instead, which is the obvious-looking move and was
	// tried, changes nothing at runtime: the mounted path stays wrong, kube-vip
	// finds neither a kubeconfig nor in-cluster credentials, and it reports
	//   could not create k8s REST config from incluster file: "/.kube/config":
	//   KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
	// while the VIP never appears.
	//
	// The file is super-admin.conf and not admin.conf because since Kubernetes
	// 1.29 admin.conf is not usable until the cluster's cluster-admins binding
	// exists, which happens later in the bootstrap.
	raw, err := KubeVIPManifest("192.168.122.99", "eth0", "6443", SuperAdminKubeconfig, "192.168.122.252", KubeVIPImage)
	if err != nil {
		t.Fatalf("KubeVIPManifest() failed: %v", err)
	}

	var pod struct {
		Spec struct {
			Containers []struct {
				Env          []struct{ Name, Value string } `yaml:"env"`
				VolumeMounts []struct {
					MountPath string `yaml:"mountPath"`
				} `yaml:"volumeMounts"`
			} `yaml:"containers"`
			Volumes []struct {
				HostPath struct {
					Path string `yaml:"path"`
				} `yaml:"hostPath"`
			} `yaml:"volumes"`
		} `yaml:"spec"`
	}
	if err := yaml.Unmarshal(raw, &pod); err != nil {
		t.Fatalf("generated manifest does not parse: %v", err)
	}

	if got := pod.Spec.Containers[0].VolumeMounts[0].MountPath; got != kubeVIPContainerKubeconfig {
		t.Errorf("the kubeconfig is mounted at %q, want the path kube-vip reads, %q",
			got, kubeVIPContainerKubeconfig)
	}
	if got := pod.Spec.Volumes[0].HostPath.Path; got != SuperAdminKubeconfig {
		t.Errorf("the host path is %q, want %q", got, SuperAdminKubeconfig)
	}

	// kube-vip must be told which namespace holds its leader-election lease.
	env := map[string]string{}
	for _, e := range pod.Spec.Containers[0].Env {
		env[e.Name] = e.Value
	}
	if env["cp_namespace"] == "" {
		t.Error("cp_namespace is unset; kube-vip needs a namespace for its leader-election lease")
	}

	// kube-vip must be told the API server address explicitly. Left to itself in
	// control-plane mode it builds "kubernetes:<port>" and depends on a host
	// alias to resolve that name, which proved unreliable for a static pod: the
	// pod's /etc/hosts had the entry and resolution still failed, and the VIP
	// never appeared.
	if addr := env["kubernetes_addr"]; addr == "" {
		t.Error("kubernetes_addr is unset; kube-vip would fall back to resolving the name \"kubernetes\"")
	} else if !strings.HasPrefix(addr, "192.168.122.252:") {
		t.Errorf("kubernetes_addr = %q, want this node's own address", addr)
	}
	if SuperAdminKubeconfig == "/etc/kubernetes/admin.conf" {
		t.Error("SuperAdminKubeconfig points at admin.conf, which does not work during bootstrap")
	}
}
