// The Vates Kube OS management API.
//
// One service, a handful of methods, authenticated with mutual TLS: the cluster
// certificate authority signs the server certificate and every client
// certificate an operator (vateskctl) or the CAPI provider presents. This is the
// node's management face, and it is what replaces SSH -- which this OS does not
// carry. See docs/API.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vates/api/v1/api.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node's Kubernetes name.
	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Whether this node runs a control plane.
	ControlPlane bool `protobuf:"varint,2,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	// The Kubernetes version the node was told to run.
	KubernetesVersion string `protobuf:"bytes,3,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// The cluster's API endpoint, host:port.
	ClusterEndpoint string `protobuf:"bytes,4,opt,name=cluster_endpoint,json=clusterEndpoint,proto3" json:"cluster_endpoint,omitempty"`
	// Whether the kubelet has registered the node and the API answers.
	Ready         bool `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetStatusResponse) GetControlPlane() bool {
	if x != nil {
		return x.ControlPlane
	}
	return false
}

func (x *GetStatusResponse) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *GetStatusResponse) GetClusterEndpoint() string {
	if x != nil {
		return x.ClusterEndpoint
	}
	return ""
}

func (x *GetStatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type GetKubeconfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKubeconfigRequest) Reset() {
	*x = GetKubeconfigRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKubeconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubeconfigRequest) ProtoMessage() {}

func (x *GetKubeconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubeconfigRequest.ProtoReflect.Descriptor instead.
func (*GetKubeconfigRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{2}
}

type GetKubeconfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A kubeconfig file, ready to write to disk and pass to `kubectl --kubeconfig`.
	Kubeconfig    []byte `protobuf:"bytes,1,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKubeconfigResponse) Reset() {
	*x = GetKubeconfigResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKubeconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKubeconfigResponse) ProtoMessage() {}

func (x *GetKubeconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKubeconfigResponse.ProtoReflect.Descriptor instead.
func (*GetKubeconfigResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetKubeconfigResponse) GetKubeconfig() []byte {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

type GetJoinMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinMaterialRequest) Reset() {
	*x = GetJoinMaterialRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinMaterialRequest) ProtoMessage() {}

func (x *GetJoinMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinMaterialRequest.ProtoReflect.Descriptor instead.
func (*GetJoinMaterialRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{4}
}

type GetJoinMaterialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A bootstrap token, "abcdef.0123456789abcdef", valid for 24 hours.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The certificate key a joining control plane passes to `kubeadm join
	// --control-plane --certificate-key`. Valid for two hours, kubeadm's rule.
	CertificateKey string `protobuf:"bytes,2,opt,name=certificate_key,json=certificateKey,proto3" json:"certificate_key,omitempty"`
	// The cluster CA's public-key hash, for kubeadm's
	// --discovery-token-ca-cert-hash.
	CaCertHash    string `protobuf:"bytes,3,opt,name=ca_cert_hash,json=caCertHash,proto3" json:"ca_cert_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinMaterialResponse) Reset() {
	*x = GetJoinMaterialResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinMaterialResponse) ProtoMessage() {}

func (x *GetJoinMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinMaterialResponse.ProtoReflect.Descriptor instead.
func (*GetJoinMaterialResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetJoinMaterialResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetJoinMaterialResponse) GetCertificateKey() string {
	if x != nil {
		return x.CertificateKey
	}
	return ""
}

func (x *GetJoinMaterialResponse) GetCaCertHash() string {
	if x != nil {
		return x.CaCertHash
	}
	return ""
}

type GetBootSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootSlotsRequest) Reset() {
	*x = GetBootSlotsRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootSlotsRequest) ProtoMessage() {}

func (x *GetBootSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetBootSlotsRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{6}
}

type GetBootSlotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The slot the node is running: "a", "b", or "" when the kernel command line
	// does not name one.
	Running string `protobuf:"bytes,1,opt,name=running,proto3" json:"running,omitempty"`
	// The boot entry loader.conf defaults to, boot counter included ("vates-b+3").
	DefaultEntry string `protobuf:"bytes,2,opt,name=default_entry,json=defaultEntry,proto3" json:"default_entry,omitempty"`
	// Each slot's entry base name on the ESP ("vates-a", "vates-b+3"), by slot.
	Entries       map[string]string `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootSlotsResponse) Reset() {
	*x = GetBootSlotsResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootSlotsResponse) ProtoMessage() {}

func (x *GetBootSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetBootSlotsResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetBootSlotsResponse) GetRunning() string {
	if x != nil {
		return x.Running
	}
	return ""
}

func (x *GetBootSlotsResponse) GetDefaultEntry() string {
	if x != nil {
		return x.DefaultEntry
	}
	return ""
}

func (x *GetBootSlotsResponse) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SetBootSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The slot to boot next: "a" or "b".
	Slot          string `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootSlotRequest) Reset() {
	*x = SetBootSlotRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootSlotRequest) ProtoMessage() {}

func (x *SetBootSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootSlotRequest.ProtoReflect.Descriptor instead.
func (*SetBootSlotRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *SetBootSlotRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type SetBootSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootSlotResponse) Reset() {
	*x = SetBootSlotResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootSlotResponse) ProtoMessage() {}

func (x *SetBootSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootSlotResponse.ProtoReflect.Descriptor instead.
func (*SetBootSlotResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{9}
}

type GetLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many lines to return per log, from the end. Zero means a default (200).
	Lines         int32 `protobuf:"varint,1,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_vates_api_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type GetLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The logs, each section headed by the file it came from, oldest line first.
	Logs          string `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_vates_api_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vates_api_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_vates_api_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_vates_api_v1_api_proto protoreflect.FileDescriptor

const file_vates_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x16vates/api/v1/api.proto\x12\fvates.api.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xc5\x01\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\rcontrol_plane\x18\x02 \x01(\bR\fcontrolPlane\x12-\n" +
	"\x12kubernetes_version\x18\x03 \x01(\tR\x11kubernetesVersion\x12)\n" +
	"\x10cluster_endpoint\x18\x04 \x01(\tR\x0fclusterEndpoint\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\"\x16\n" +
	"\x14GetKubeconfigRequest\"7\n" +
	"\x15GetKubeconfigResponse\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\fR\n" +
	"kubeconfig\"\x18\n" +
	"\x16GetJoinMaterialRequest\"z\n" +
	"\x17GetJoinMaterialResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x0fcertificate_key\x18\x02 \x01(\tR\x0ecertificateKey\x12 \n" +
	"\fca_cert_hash\x18\x03 \x01(\tR\n" +
	"caCertHash\"\x15\n" +
	"\x13GetBootSlotsRequest\"\xdc\x01\n" +
	"\x14GetBootSlotsResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\tR\arunning\x12#\n" +
	"\rdefault_entry\x18\x02 \x01(\tR\fdefaultEntry\x12I\n" +
	"\aentries\x18\x03 \x03(\v2/.vates.api.v1.GetBootSlotsResponse.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x12SetBootSlotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"\x15\n" +
	"\x13SetBootSlotResponse\"&\n" +
	"\x0eGetLogsRequest\x12\x14\n" +
	"\x05lines\x18\x01 \x01(\x05R\x05lines\"%\n" +
	"\x0fGetLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs2\x85\x04\n" +
	"\bVatesAPI\x12L\n" +
	"\tGetStatus\x12\x1e.vates.api.v1.GetStatusRequest\x1a\x1f.vates.api.v1.GetStatusResponse\x12X\n" +
	"\rGetKubeconfig\x12\".vates.api.v1.GetKubeconfigRequest\x1a#.vates.api.v1.GetKubeconfigResponse\x12^\n" +
	"\x0fGetJoinMaterial\x12$.vates.api.v1.GetJoinMaterialRequest\x1a%.vates.api.v1.GetJoinMaterialResponse\x12U\n" +
	"\fGetBootSlots\x12!.vates.api.v1.GetBootSlotsRequest\x1a\".vates.api.v1.GetBootSlotsResponse\x12R\n" +
	"\vSetBootSlot\x12 .vates.api.v1.SetBootSlotRequest\x1a!.vates.api.v1.SetBootSlotResponse\x12F\n" +
	"\aGetLogs\x12\x1c.vates.api.v1.GetLogsRequest\x1a\x1d.vates.api.v1.GetLogsResponseB;Z9github.com/vatesfr/vates-kube-os/proto/vates/api/v1;apiv1b\x06proto3"

var (
	file_vates_api_v1_api_proto_rawDescOnce sync.Once
	file_vates_api_v1_api_proto_rawDescData []byte
)

func file_vates_api_v1_api_proto_rawDescGZIP() []byte {
	file_vates_api_v1_api_proto_rawDescOnce.Do(func() {
		file_vates_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vates_api_v1_api_proto_rawDesc), len(file_vates_api_v1_api_proto_rawDesc)))
	})
	return file_vates_api_v1_api_proto_rawDescData
}

var file_vates_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_vates_api_v1_api_proto_goTypes = []any{
	(*GetStatusRequest)(nil),        // 0: vates.api.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 1: vates.api.v1.GetStatusResponse
	(*GetKubeconfigRequest)(nil),    // 2: vates.api.v1.GetKubeconfigRequest
	(*GetKubeconfigResponse)(nil),   // 3: vates.api.v1.GetKubeconfigResponse
	(*GetJoinMaterialRequest)(nil),  // 4: vates.api.v1.GetJoinMaterialRequest
	(*GetJoinMaterialResponse)(nil), // 5: vates.api.v1.GetJoinMaterialResponse
	(*GetBootSlotsRequest)(nil),     // 6: vates.api.v1.GetBootSlotsRequest
	(*GetBootSlotsResponse)(nil),    // 7: vates.api.v1.GetBootSlotsResponse
	(*SetBootSlotRequest)(nil),      // 8: vates.api.v1.SetBootSlotRequest
	(*SetBootSlotResponse)(nil),     // 9: vates.api.v1.SetBootSlotResponse
	(*GetLogsRequest)(nil),          // 10: vates.api.v1.GetLogsRequest
	(*GetLogsResponse)(nil),         // 11: vates.api.v1.GetLogsResponse
	nil,                             // 12: vates.api.v1.GetBootSlotsResponse.EntriesEntry
}
var file_vates_api_v1_api_proto_depIdxs = []int32{
	12, // 0: vates.api.v1.GetBootSlotsResponse.entries:type_name -> vates.api.v1.GetBootSlotsResponse.EntriesEntry
	0,  // 1: vates.api.v1.VatesAPI.GetStatus:input_type -> vates.api.v1.GetStatusRequest
	2,  // 2: vates.api.v1.VatesAPI.GetKubeconfig:input_type -> vates.api.v1.GetKubeconfigRequest
	4,  // 3: vates.api.v1.VatesAPI.GetJoinMaterial:input_type -> vates.api.v1.GetJoinMaterialRequest
	6,  // 4: vates.api.v1.VatesAPI.GetBootSlots:input_type -> vates.api.v1.GetBootSlotsRequest
	8,  // 5: vates.api.v1.VatesAPI.SetBootSlot:input_type -> vates.api.v1.SetBootSlotRequest
	10, // 6: vates.api.v1.VatesAPI.GetLogs:input_type -> vates.api.v1.GetLogsRequest
	1,  // 7: vates.api.v1.VatesAPI.GetStatus:output_type -> vates.api.v1.GetStatusResponse
	3,  // 8: vates.api.v1.VatesAPI.GetKubeconfig:output_type -> vates.api.v1.GetKubeconfigResponse
	5,  // 9: vates.api.v1.VatesAPI.GetJoinMaterial:output_type -> vates.api.v1.GetJoinMaterialResponse
	7,  // 10: vates.api.v1.VatesAPI.GetBootSlots:output_type -> vates.api.v1.GetBootSlotsResponse
	9,  // 11: vates.api.v1.VatesAPI.SetBootSlot:output_type -> vates.api.v1.SetBootSlotResponse
	11, // 12: vates.api.v1.VatesAPI.GetLogs:output_type -> vates.api.v1.GetLogsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_vates_api_v1_api_proto_init() }
func file_vates_api_v1_api_proto_init() {
	if File_vates_api_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vates_api_v1_api_proto_rawDesc), len(file_vates_api_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vates_api_v1_api_proto_goTypes,
		DependencyIndexes: file_vates_api_v1_api_proto_depIdxs,
		MessageInfos:      file_vates_api_v1_api_proto_msgTypes,
	}.Build()
	File_vates_api_v1_api_proto = out.File
	file_vates_api_v1_api_proto_goTypes = nil
	file_vates_api_v1_api_proto_depIdxs = nil
}
