// The Vates Kube OS management API.
//
// One service, a handful of methods, authenticated with mutual TLS: the cluster
// certificate authority signs the server certificate and every client
// certificate an operator (vateskctl) or the CAPI provider presents. This is the
// node's management face, and it is what replaces SSH -- which this OS does not
// carry. See docs/API.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vates/api/v1/api.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VatesAPI_GetStatus_FullMethodName       = "/vates.api.v1.VatesAPI/GetStatus"
	VatesAPI_GetKubeconfig_FullMethodName   = "/vates.api.v1.VatesAPI/GetKubeconfig"
	VatesAPI_GetJoinMaterial_FullMethodName = "/vates.api.v1.VatesAPI/GetJoinMaterial"
	VatesAPI_GetBootSlots_FullMethodName    = "/vates.api.v1.VatesAPI/GetBootSlots"
	VatesAPI_SetBootSlot_FullMethodName     = "/vates.api.v1.VatesAPI/SetBootSlot"
	VatesAPI_GetLogs_FullMethodName         = "/vates.api.v1.VatesAPI/GetLogs"
)

// VatesAPIClient is the client API for VatesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VatesAPI is served on port 50000 by a running node.
type VatesAPIClient interface {
	// GetStatus reports what the node is and how far its bring-up has come. It is
	// the call a provider polls to know a machine is ready.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetKubeconfig returns the admin kubeconfig of the cluster the node belongs
	// to. A control plane reads it from its own disk; the provider stores it so
	// `clusterctl get kubeconfig` can hand it out.
	GetKubeconfig(ctx context.Context, in *GetKubeconfigRequest, opts ...grpc.CallOption) (*GetKubeconfigResponse, error)
	// GetJoinMaterial returns fresh credentials for a machine that joins this
	// cluster: a bootstrap token, the certificate key a joining control plane
	// fetches the shared certificates with, and the CA hash it verifies the
	// cluster with.
	//
	// Only a bootstrapped control plane can answer. Under CAPI the provider holds
	// the cluster CA and issues these itself, so it does not call this; without
	// CAPI the node is the only holder, and this API is the only channel -- which
	// is the whole reason it exists.
	GetJoinMaterial(ctx context.Context, in *GetJoinMaterialRequest, opts ...grpc.CallOption) (*GetJoinMaterialResponse, error)
	// GetBootSlots reports the A/B state: which root the node is running, and
	// which boot entry loader.conf points at. The two roots are the disk's rootA
	// and rootB; see docs/IMMUTABILITY.md.
	GetBootSlots(ctx context.Context, in *GetBootSlotsRequest, opts ...grpc.CallOption) (*GetBootSlotsResponse, error)
	// SetBootSlot points the NEXT boot at a slot and marks its entry a trial, so a
	// slot that does not come up is rolled back from automatically. It does NOT
	// write the slot: the caller -- the provider, or an operator with an image --
	// has done that, or the node would boot the old system again. This is the only
	// way to switch, because the node has no shell.
	SetBootSlot(ctx context.Context, in *SetBootSlotRequest, opts ...grpc.CallOption) (*SetBootSlotResponse, error)
	// GetLogs returns the tail of the node's own logs -- PID 1's and each
	// supervised service's. A node has no shell and no sshd, so when bring-up
	// fails this is the only place an operator can see WHY, and it answers even
	// when the node never became Ready.
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type vatesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVatesAPIClient(cc grpc.ClientConnInterface) VatesAPIClient {
	return &vatesAPIClient{cc}
}

func (c *vatesAPIClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, VatesAPI_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vatesAPIClient) GetKubeconfig(ctx context.Context, in *GetKubeconfigRequest, opts ...grpc.CallOption) (*GetKubeconfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKubeconfigResponse)
	err := c.cc.Invoke(ctx, VatesAPI_GetKubeconfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vatesAPIClient) GetJoinMaterial(ctx context.Context, in *GetJoinMaterialRequest, opts ...grpc.CallOption) (*GetJoinMaterialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJoinMaterialResponse)
	err := c.cc.Invoke(ctx, VatesAPI_GetJoinMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vatesAPIClient) GetBootSlots(ctx context.Context, in *GetBootSlotsRequest, opts ...grpc.CallOption) (*GetBootSlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootSlotsResponse)
	err := c.cc.Invoke(ctx, VatesAPI_GetBootSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vatesAPIClient) SetBootSlot(ctx context.Context, in *SetBootSlotRequest, opts ...grpc.CallOption) (*SetBootSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBootSlotResponse)
	err := c.cc.Invoke(ctx, VatesAPI_SetBootSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vatesAPIClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, VatesAPI_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VatesAPIServer is the server API for VatesAPI service.
// All implementations must embed UnimplementedVatesAPIServer
// for forward compatibility.
//
// VatesAPI is served on port 50000 by a running node.
type VatesAPIServer interface {
	// GetStatus reports what the node is and how far its bring-up has come. It is
	// the call a provider polls to know a machine is ready.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetKubeconfig returns the admin kubeconfig of the cluster the node belongs
	// to. A control plane reads it from its own disk; the provider stores it so
	// `clusterctl get kubeconfig` can hand it out.
	GetKubeconfig(context.Context, *GetKubeconfigRequest) (*GetKubeconfigResponse, error)
	// GetJoinMaterial returns fresh credentials for a machine that joins this
	// cluster: a bootstrap token, the certificate key a joining control plane
	// fetches the shared certificates with, and the CA hash it verifies the
	// cluster with.
	//
	// Only a bootstrapped control plane can answer. Under CAPI the provider holds
	// the cluster CA and issues these itself, so it does not call this; without
	// CAPI the node is the only holder, and this API is the only channel -- which
	// is the whole reason it exists.
	GetJoinMaterial(context.Context, *GetJoinMaterialRequest) (*GetJoinMaterialResponse, error)
	// GetBootSlots reports the A/B state: which root the node is running, and
	// which boot entry loader.conf points at. The two roots are the disk's rootA
	// and rootB; see docs/IMMUTABILITY.md.
	GetBootSlots(context.Context, *GetBootSlotsRequest) (*GetBootSlotsResponse, error)
	// SetBootSlot points the NEXT boot at a slot and marks its entry a trial, so a
	// slot that does not come up is rolled back from automatically. It does NOT
	// write the slot: the caller -- the provider, or an operator with an image --
	// has done that, or the node would boot the old system again. This is the only
	// way to switch, because the node has no shell.
	SetBootSlot(context.Context, *SetBootSlotRequest) (*SetBootSlotResponse, error)
	// GetLogs returns the tail of the node's own logs -- PID 1's and each
	// supervised service's. A node has no shell and no sshd, so when bring-up
	// fails this is the only place an operator can see WHY, and it answers even
	// when the node never became Ready.
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	mustEmbedUnimplementedVatesAPIServer()
}

// UnimplementedVatesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVatesAPIServer struct{}

func (UnimplementedVatesAPIServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedVatesAPIServer) GetKubeconfig(context.Context, *GetKubeconfigRequest) (*GetKubeconfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKubeconfig not implemented")
}
func (UnimplementedVatesAPIServer) GetJoinMaterial(context.Context, *GetJoinMaterialRequest) (*GetJoinMaterialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJoinMaterial not implemented")
}
func (UnimplementedVatesAPIServer) GetBootSlots(context.Context, *GetBootSlotsRequest) (*GetBootSlotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootSlots not implemented")
}
func (UnimplementedVatesAPIServer) SetBootSlot(context.Context, *SetBootSlotRequest) (*SetBootSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBootSlot not implemented")
}
func (UnimplementedVatesAPIServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedVatesAPIServer) mustEmbedUnimplementedVatesAPIServer() {}
func (UnimplementedVatesAPIServer) testEmbeddedByValue()                  {}

// UnsafeVatesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VatesAPIServer will
// result in compilation errors.
type UnsafeVatesAPIServer interface {
	mustEmbedUnimplementedVatesAPIServer()
}

func RegisterVatesAPIServer(s grpc.ServiceRegistrar, srv VatesAPIServer) {
	// If the following call panics, it indicates UnimplementedVatesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VatesAPI_ServiceDesc, srv)
}

func _VatesAPI_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VatesAPI_GetKubeconfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKubeconfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).GetKubeconfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_GetKubeconfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).GetKubeconfig(ctx, req.(*GetKubeconfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VatesAPI_GetJoinMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJoinMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).GetJoinMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_GetJoinMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).GetJoinMaterial(ctx, req.(*GetJoinMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VatesAPI_GetBootSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).GetBootSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_GetBootSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).GetBootSlots(ctx, req.(*GetBootSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VatesAPI_SetBootSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).SetBootSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_SetBootSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).SetBootSlot(ctx, req.(*SetBootSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VatesAPI_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VatesAPIServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VatesAPI_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VatesAPIServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VatesAPI_ServiceDesc is the grpc.ServiceDesc for VatesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VatesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vates.api.v1.VatesAPI",
	HandlerType: (*VatesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _VatesAPI_GetStatus_Handler,
		},
		{
			MethodName: "GetKubeconfig",
			Handler:    _VatesAPI_GetKubeconfig_Handler,
		},
		{
			MethodName: "GetJoinMaterial",
			Handler:    _VatesAPI_GetJoinMaterial_Handler,
		},
		{
			MethodName: "GetBootSlots",
			Handler:    _VatesAPI_GetBootSlots_Handler,
		},
		{
			MethodName: "SetBootSlot",
			Handler:    _VatesAPI_SetBootSlot_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _VatesAPI_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vates/api/v1/api.proto",
}
